import {
    spfOne,
    spfTwo,
    spfThree,
    spfFour,
    bestSellerOne,
    bestSellerTwo,
    bestSellerThree,
    bestSellerFour,
    newArrOne,
    newArrTwo,
    newArrThree,
    newArrFour,
    imp1,
    imp2,
    imp4,
    imp5,
    imp6,
    imp7,
    imp8,
    imp9,
    encre1,
    encre2,
    encre3,
    encre4,
    ruban1,
    ruban2,
    ruban3,
    ruban4,
    bac1,
    bac2,
    bac3,
    bac4,
    IMP1,
    IMP2,
    IMP3,
    IMP4,
    IMP5,
    IMP6,
    IMP7,
    IMP8,
    IMP9,
    hp1,
    hp2,
    hp3,
    ricoh1,
    ricoh2,
    ricoh3,
    ricoh4,
    ricoh5,
    es1,
    es2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
    {
        _id: 1001,
        title: "Home",
        link: "/",
    },
    {
        _id: 1002,
        title: "Shop",
        link: "/shop",
    },
    {
        _id: 1003,
        title: "About",
        link: "/about",
    },
    {
        _id: 1004,
        title: "Contact",
        link: "contact",
    },
    {
        _id: 1005,
        title: "Journal",
        link: "/journal",
    },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
    {
        _id: "201",
        img: imp1,
        productName: "impqwerty",
        price: "35.00",
        color: "Blank and White",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "202",
        img: imp2,
        productName: "impqwerty",
        price: "180.00",
        color: "Gray",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "203",
        img: imp4,
        productName: "impqwerty",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "204",
        img: imp5,
        productName: "impqwerty",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "205",
        img: imp6,
        productName: "impqwerty",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "206",
        img: imp7,
        productName: "impqwerty",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "207",
        img: imp8,
        productName: "impqwerty",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "208",
        img: imp9,
        productName: "impqwerty",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "impqwerty",
    },
    {
        _id: "209",
        img: encre1,
        productName: "encre",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "ancre",
    },
    {
        _id: "210",
        img: encre2,
        productName: "encre",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "ancre",
    },
    {
        _id: "211",
        img: encre3,
        productName: "encre",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "ancre",
    },
    {
        _id: "212",
        img: encre4,
        productName: "encre",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "ancre",
    },
    {
        _id: "213",
        img: ruban1,
        productName: "Ruban",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "214",
        img: ruban2,
        productName: "Ruban",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "215",
        img: ruban3,
        productName: "Ruban",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "216",
        img: ruban4,
        productName: "Ruban",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "217",
        img: bac1,
        productName: "Bac",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
    {
        _id: "219",
        img: bac2,
        productName: "Bac",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
    {
        _id: "220",
        img: bac3,
        productName: "Bac",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
    {
        _id: "221",
        img: bac4,
        productName: "Bac",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
    {
        _id: "201",
        img: IMP1,
        productName: "impqwerty PAN",
        price: "35.00",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    {
        _id: "202",
        img: IMP2,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "203",
        img: IMP3,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    {
        _id: "2005",
        img: IMP4,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "20005",
        img: IMP5,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "206",
        img: IMP6,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "207",
        img: IMP7,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "208",
        img: IMP8,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "ILorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    {
        _id: "233",
        img: IMP9,
        productName: "impqwerty PAN",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Pantum",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [],
    },
    {
        _id: "220",
        img: bac3,
        productName: "Bac de dechet",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
    {
        _id: "221",
        img: bac4,
        productName: "Bac de dechet",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
    {
        _id: "215",
        img: ruban3,
        productName: "Ruban",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "216",
        img: ruban4,
        productName: "Ruban",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "209",
        img: encre1,
        productName: "encre",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Encre",
    },
    {
        _id: "210",
        img: encre2,
        productName: "encre",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Encre",
    },

    {
        _id: "211",
        img: encre3,
        productName: "encre",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Encre",
    },
    {
        _id: "212",
        img: encre4,
        productName: "encre",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Encre",
    },
    {
        _id: "213",
        img: ruban1,
        productName: "Ruban",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },
    {
        _id: "214",
        img: ruban2,
        productName: "Ruban",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Ruban",
    },

    {
        _id: "217",
        img: bac1,
        productName: "Bac de dechet",
        price: "25.00",
        color: "Mixed",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },
    {
        _id: "219",
        img: bac2,
        productName: "Bac de dechet",
        price: "220.00",
        color: "Black",
        badge: true,
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
        cat: "Bac",
    },

    // =================== impqwerty hp =================

    {
        _id: "hp1",
        img: hp1,
        productName:
            "impqwerty HP ",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Hp",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "hp2",
        img: hp2,
        productName: "impqwerty HP",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Hp",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [],
    },

    {
        _id: "hp3",
        img: hp3,
        productName: "impqwerty HP",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Hp",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    // =================== impqwerty ricoh =================
    {
        _id: "ricoh1",
        img: ricoh1,
        productName: "impqwerty RIC",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Ricoh",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "ricoh2",
        img: ricoh2,
        productName: "impqwerty RIC",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Ricoh",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    {
        _id: "ricoh3",
        img: ricoh3,
        productName: "impqwerty RIC",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Ricoh",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    {
        _id: "ricoh4",
        img: ricoh4,
        productName: "impqwerty RIC",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Ricoh",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
    {
        _id: "ricoh5",
        img: ricoh5,
        productName: "impqwerty RIC",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Ricoh",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    // =================== impqwerty ricoh =================

    {
        _id: "es1",
        img: es1,
        productName: "impqwerty ES",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Epson",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },

    {
        _id: "espson2",
        img: es2,
        productName: "impqwerty EPS",
        price: "450",
        color: "Blanc",
        badge: true,
        brand: "Epson",
        des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eros leo, viverra sit amet ipsum nec, vehicula accumsan libero. Quisque at nunc quam. Nam sit amet semper erat. Vestibulum pulvinar justo ac est gravida lacinia. Aliquam erat volutpat. Sed imperdiet molestie nunc eu efficitur. Aenean egestas, arcu a aliquet finibus.",
        cat: "impqwerty",
        ficheTech: [
            { label: "Shampoo ", value: "Water " },
            { label: "Volume ", value: "2" },

            { label: "First shot in eye ", value: "Less than 7.8s       " },
            { label: "Maximum Monthly Duty shot in eye", value: "15,000 " },
            {
                label: "Recommended monthly use ",
                value: "everyday ",
            },
        ],
    },
];
